// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT8HVLUPSKmdNM15ofqgaLguoHSUzglME',
    appId: '1:863512352678:web:a5475f158dcc6eb4576167',
    messagingSenderId: '863512352678',
    projectId: 'routeats',
    authDomain: 'routeats.firebaseapp.com',
    storageBucket: 'routeats.firebasestorage.app',
    measurementId: 'G-RDXV51RVB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYbwJYiv8QWbiDyX-l-NwSnWUbGI5fzQk',
    appId: '1:863512352678:android:369612eb44110c99576167',
    messagingSenderId: '863512352678',
    projectId: 'routeats',
    storageBucket: 'routeats.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZpuJFuUlZq2imDzpZcT2XzNs6u8gyJfI',
    appId: '1:863512352678:ios:5b69491d07a1491f576167',
    messagingSenderId: '863512352678',
    projectId: 'routeats',
    storageBucket: 'routeats.firebasestorage.app',
    iosBundleId: 'com.example.routeeats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZpuJFuUlZq2imDzpZcT2XzNs6u8gyJfI',
    appId: '1:863512352678:ios:5b69491d07a1491f576167',
    messagingSenderId: '863512352678',
    projectId: 'routeats',
    storageBucket: 'routeats.firebasestorage.app',
    iosBundleId: 'com.example.routeeats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT8HVLUPSKmdNM15ofqgaLguoHSUzglME',
    appId: '1:863512352678:web:7d2c80ce5712161a576167',
    messagingSenderId: '863512352678',
    projectId: 'routeats',
    authDomain: 'routeats.firebaseapp.com',
    storageBucket: 'routeats.firebasestorage.app',
    measurementId: 'G-S5S86E0GNP',
  );
}
